---
# file: ./macos/tasks/main.yml

- block:

  - name: use fish as login shell
    user:
      name: '{{ ansible_env.USER }}'
      shell: /usr/local/bin/fish
    tags:
      - shell

  - name: DNS setting
    shell: networksetup -setdnsservers Wi-Fi 8.8.8.8 8.8.4.4
    tags:
      - dns

  - block:
    # check defaults
    # $ defaults read
    - name: set osx defaults
      osx_defaults:
        domain: "{{ item.domain }}"
        key: "{{ item.key }}"
        type: "{{ item.type }}"
        value: "{{ item.value }}"
      with_items: "{{ settings }}"
    tags:
      - osx_defaults
