---
# file: ./homebrew/tasks/main.yml

- block:

  - name: Homebrew update
    homebrew:
      update_homebrew: true

  - name: Homebrew tap
    homebrew_tap:
      name: "{{ item }}"
      state: present
    with_items: "{{ taps }}"

  - name: Homebrew packages install
    homebrew:
      name: "{{ item.name }}"
      state: "{{ item.state | default('present') }}"
    with_items: "{{ packages }}"

  tags:
    - homebrew
